// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('C:/Users/Administrator/Documents/Projects/Personal/Planning-poker-v3/src/components/HelloWorld.vue')['default']
    IMdiClose: typeof import('~icons/mdi/close')['default']
    IMdiGoogle: typeof import('~icons/mdi/google')['default']
    IMdiHome: typeof import('~icons/mdi/home')['default']
    IMdiPlus: typeof import('~icons/mdi/plus')['default']
    Index: typeof import('C:/Users/Administrator/Documents/Projects/Personal/Planning-poker-v3/src/components/Logo/Index.vue')['default']
    LightSwitch: typeof import('C:/Users/Administrator/Documents/Projects/Personal/Planning-poker-v3/src/components/LightSwitch.vue')['default']
    Logo: typeof import('C:/Users/Administrator/Documents/Projects/Personal/Planning-poker-v3/src/components/Logo/Index.vue')['default']
    LogoText: typeof import('C:/Users/Administrator/Documents/Projects/Personal/Planning-poker-v3/src/components/Logo/Text.vue')['default']
    Lottie: typeof import('C:/Users/Administrator/Documents/Projects/Personal/Planning-poker-v3/src/components/Lottie.vue')['default']
    LottieWrapper: typeof import('C:/Users/Administrator/Documents/Projects/Personal/Planning-poker-v3/src/components/LottieWrapper.vue')['default']
    MainLogo: typeof import('C:/Users/Administrator/Documents/Projects/Personal/Planning-poker-v3/src/components/MainLogo.vue')['default']
    MenuLeft: typeof import('C:/Users/Administrator/Documents/Projects/Personal/Planning-poker-v3/src/components/MenuLeft.vue')['default']
    MyButton: typeof import('C:/Users/Administrator/Documents/Projects/Personal/Planning-poker-v3/src/components/MyButton.vue')['default']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NBreadcrumb: typeof import('naive-ui')['NBreadcrumb']
    NBreadcrumbItem: typeof import('naive-ui')['NBreadcrumbItem']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NewDeckModal: typeof import('C:/Users/Administrator/Documents/Projects/Personal/Planning-poker-v3/src/components/NewDeckModal.vue')['default']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NH3: typeof import('naive-ui')['NH3']
    NH5: typeof import('naive-ui')['NH5']
    NInput: typeof import('naive-ui')['NInput']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NMenu: typeof import('naive-ui')['NMenu']
    NModal: typeof import('naive-ui')['NModal']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NP: typeof import('naive-ui')['NP']
    NPageHeader: typeof import('naive-ui')['NPageHeader']
    NSelect: typeof import('naive-ui')['NSelect']
    NSpace: typeof import('naive-ui')['NSpace']
    NStep: typeof import('naive-ui')['NStep']
    NSteps: typeof import('naive-ui')['NSteps']
    NSwitch: typeof import('naive-ui')['NSwitch']
    NThemeEditor: typeof import('naive-ui')['NThemeEditor']
    Text: typeof import('C:/Users/Administrator/Documents/Projects/Personal/Planning-poker-v3/src/components/Logo/Text.vue')['default']
  }
}

export { }
